user: t_analytics #env var PGUSER
database: t_analytics #env var PGDATABASE
password: postgres #env var: PGPASSWORD
host: localhost #default : 'localhost'
port: 5432 #env var: PGPORT
max: 10  #max number of clients in the pool
idleTimeoutMillis: 30000 # how long a client is allowed to remain idle before being closed
